name: Update today.json and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update today.json file
        run: bin/update
      - name: Deploy to GitHub Pages
        run: yarn && yarn deploy
