name: Update today.json and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update today.json
        run: bin/update
      - name: Build
        run: yarn && yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
