name: Update today.json and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update today.json file
        run: bin/update
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'Pedro Martins'
          git config --global user.email 'pedrosbarbosamartins@gmail.com'
          yarn && yarn deploy
